-   repo: https://github.com/chriskuehl/pre-commit-hooks.git
    sha: cd3f867cafee3488a93a13f97bf7fdab329c996e
    hooks:
    -   id: autopep8-wrapper
        language_version: python3
        exclude: ^vendor/
    -   id: check-added-large-files
    -   id: check-docstring-first
        language_version: python3
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
    -   id: detect-private-key
    -   id: double-quote-string-fixer
        language_version: python3
    -   id: end-of-file-fixer
        exclude: ^ocfweb/static/fonts/bootstrap/
    -   id: flake8
        language_version: python3
        exclude: ^vendor/
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        exclude: ^ocfweb/static/fonts/bootstrap/
-   repo: https://github.com/chriskuehl/reorder_python_imports.git
    sha: 138f897f7d53c53dd4535dc377764fa3a58e310c
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/chriskuehl/pre-commit-hooks-1.git
    sha: cb3b03ba29a70be8ff4702429ea331cfc61b87c8
    hooks:
    -   id: remove-tabs
        exclude: (Makefile|debian/rules)$
        language_version: python2.7
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    sha: 3eb13b9647543ad4d6a62c8be8a9131e3b99b96a
    hooks:
    -   id: scss-lint
-   repo: local
    hooks:
    -   id: no-top-level-header
        language: pcre
        name: No top-level headers (markdown)
        entry: ^#\s
        types: [markdown]
    # In Django, if you have an app like "announcements" and another app like
    # "docs", it's not okay for both to provide templates with the same name
    # (e.g. "index.html") since they all get thrown onto the same templates
    # path. One of the applications' index.html will arbitrarily always be
    # shown on both of the applications.
    #
    # To avoid this undesired behavior, the hook below forces you to prefix the
    # templates with some directory first. In practice, your templates should
    # all be at ocfweb/$app/templates/$app/.
    #
    # This kinda sucks, but that's the world we live in.
    # https://stackoverflow.com/questions/3092865/django-view-load-template-from-calling-apps-dir-first
    # https://stackoverflow.com/questions/30229600/django-template-tags-with-same-name
    -   id: app-templates-prefixed-with-app-name
        language: system
        name: App templates must be prefixed with app name
        entry: bash -c 'echo "Make sure to prefix your template directories! (See .pre-commit-config.yaml for details)" && exit 1'
        files: ^ocfweb/[^/]+/templates/[^/]+\.html$
