linters:
    LeadingZero:
        style: include_zero

    NestingDepth:
        enabled: false

    SelectorDepth:
        enabled: false

    ColorVariable:
        enabled: false

    PlaceholderInExtend:
        enabled: false

    # why does anyone think this is a good idea?
    PropertySortOrder:
        enabled: false
